version: '3.4'

services:
  game.api:
    image: ${DOCKER_REGISTRY-}gameapi
    networks:
      - thor
    build:
      context: .
      dockerfile: Services/Game/Game.Api/Dockerfile

  redis:
    image: redis
    container_name: redis
    restart: unless-stopped
    ports:
      - 6379:6379
    networks:
      - thor

networks:
  thor:
    name: thor-network